/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/historia': typeof HistoriaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/novidades': typeof NovidadesRoute
  '/ofertas': typeof OfertasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/historia': typeof HistoriaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/novidades': typeof NovidadesRoute
  '/ofertas': typeof OfertasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/historia': typeof HistoriaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/novidades': typeof NovidadesRoute
  '/ofertas': typeof OfertasRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cardapio'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/historia'
    | '/localizacao'
    | '/novidades'
    | '/ofertas'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardapio'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/historia'
    | '/localizacao'
    | '/novidades'
    | '/ofertas'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/cardapio'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/faq'
    | '/historia'
    | '/localizacao'
    | '/novidades'
    | '/ofertas'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardapioRoute: typeof CardapioRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  HistoriaRoute: typeof HistoriaRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  NovidadesRoute: typeof NovidadesRoute
  OfertasRoute: typeof OfertasRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardapioRoute: CardapioRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  HistoriaRoute: HistoriaRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  NovidadesRoute: NovidadesRoute,
  OfertasRoute: OfertasRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
